name: Coffee Sales Project for IDS706

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-cov flake8
    - name: Lint with flake8
      run: flake8 coffee_analysis.py
    - name: Run tests
      run: pytest --cov=coffee_analysis
